build:
  stage: build
  image: node
  script:
    - npm install
    - npm build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp public s3://$S3_BUCKET --recursive --acl public-read
