build:
  stage: build
  image: node
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp build s3://$S3_BUCKET --recursive --acl public-read
